### ISSUE TITLE
Error upgrading to BC15 CU3 Task 6

### ISSUE THREAD

**Issue by jignaciodelaplaza** [MicrosoftDocs/dynamics365smb-devitpro-pb#1023]
Hello

I am upgrading a Cronus BC14 CU8 to BC15 CU3. I am not working in a multitenant environment. I am using the official guide (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application#feedback)

In task 6, point 4 (Publish the new versions of Microsoft extensions) I am trying to publish new versions of Microsoft extensions located in the Applications folder of the installation media (DVD).

I get an error and I am unable to publish this extensions, because "Application" package is not found.

**_PS C:\Windows\system32> Publish-NAVApp -ServerInstance BC150 -Path "C:\Temp\150\Applications\AMCBanking365Fundamentals\Source\AMCBanking365Fundamentals.app"
ADVERTENCIA: Caution: Your program license expires in 7 days.
Publish-NAVApp : A package with name 'Application', and a version compatible with '15.3.0.0' could not be found.
En línea: 1 Carácter: 1
+ Publish-NAVApp -ServerInstance BC150 -Path "C:\Temp\150\Applications\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC150/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp_**

I have tried to upgrade a 2009SP1 (2009SP1 --> 2015 CU33 --> BC14 CU8 --> BC15 CU3) version and got this error, but now, I am trying with a Cronus BC14 CU8 (to try with a 100% standard BC version) and get the same error. 

I think I am skiping any step, but I don't know what. Any idea?

Thanks

**Comment by jswymer** [comment]
Hello,

I think the reason is that starting in 15.3, we introduced the Microsoft_Application extension. You can read about this extension [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-application-app-file). 

For your scenario, you'll need to publish, sync, and install this extension in order to publish and install other Microsoft extensions. Unfortunately, the article you are looking at has not been updated. You can look at [the Publish and install Microsoft_Application extension section in Installing and Update article](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15#publish-and-install-microsoft_application-extension-update-to-153-and-later-only) to get an idea of what needs to be done. 

In the meantime, we will try to update the article. Sorry for the inconvenience. I hope this helps. Thanks for the feedback.

**Comment by jswymer** [comment]
Hello, the article has been updated. We hope this helps. Thanks for the feedback!
