### ISSUE TITLE
Please explain

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1034]
Neither do I understand the meaning of "count of captions property", nor do I know how to fix it. 
Could this be specified in detail, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89f0372d-f152-bb4d-5924-741bee4dad37
* Version Independent ID: 4e34b70e-cbfd-3f6f-3267-17bd594448e4
* Content: [The count of captions property is wrong. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/codecop-aa0224-countofoptionscaptioniswrong)
* Content Source: [dev-itpro/developer/analyzers/codecop-aa0224-countofoptionscaptioniswrong.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/codecop-aa0224-countofoptionscaptioniswrong.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback and sorry for the delayed response. 

This rule was incorrectly formulated, it should say "The count of option captions specified in the OptionCaption property is wrong." Therefore, in order to fix this, you just need to ensure that the number of option captions specified in the **OptionCaption** property matches the number of values available for an option variable or an option field on a page or report.

The documentation has been corrected and enhanced with this information, and the changes will be visible with the next refresh.

**Comment by NKarolak** [comment]
Great, thank you! :-)
