### ISSUE TITLE
The syntax does not match the example.

### ISSUE THREAD

**Issue by KristjanGaukur** [MicrosoftDocs/dynamics365smb-devitpro-pb#1212]
In the Syntax there are two variables declared, 1 protected and 1 local.
In the Example only a protected variable is declared in the master page, which then seems to be accessed directly in the extention.
So, is the local variable in the Syntax not necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d3bb501-007c-dd1a-66ac-bdbb77d748bb
* Version Independent ID: 3e48a1c7-d767-983e-2597-fb095c28885d
* Content: [Protected Variables - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-protected-variables)
* Content Source: [dev-itpro/developer/devenv-protected-variables.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-protected-variables.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. The Syntax section only serves to illustrate how to define a protected versus a local variable. There is no coherence between the Syntax and Example. We will update the topic Syntax section to only show the protected declaration to avoid any confusion. This will be fixed with the next doc refresh. Thanks.
