### ISSUE TITLE
Task 10. Step 4. Need clarification about skipping this step

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-devitpro-pb#1233]
There is a tip in task 3 (Create empty extensions System, Base, and customization extensions) that says:

> You can skip this step, then manually run Install-NavApp instead.

So if we use this tip, I understand that we don't need Task 10 step 4 (Synchronize the empty system application, base application, and customization extensions.

); but when do we need to do Install-NavApp equivalent to this step?

What would the Install-NavApp full commands be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8b2a8e-89a9-dda2-7d06-c433f2127044
* Version Independent ID: 4a968a4c-8ad7-8d9b-b966-b08daf4bda9a
* Content: [Upgrading Customized C/AL Application to Microsoft Base Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-to-microsoft-base-app)
* Content Source: [dev-itpro/upgrade/upgrade-to-microsoft-base-app.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrade-to-microsoft-base-app.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

Sorry, the article isn't clear on this. You can skip Task 3 for the system application, base application, or custom extensions if you don't have to run a data upgrade code for these extensions.

If you can skip Task 3, then you skip Task 10 step 4 (syncing the extensions) as you state. 

When you get to Task 15, instead of running Start-NAVAppDataUpgrade on the extensions, you run Install-NAVApp:

```
Install-NAVApp -ServerInstance <BC16 server instance> -Name "<extension name>" -Version <extension version>
```
I hope this answers your questions. Otherwise, let us know. We will work on making this more clear in the article.

**Comment by jswymer** [comment]
We've made some updates to the article, which we will publish soon. Thanks for the feedback!
