### ISSUE TITLE
with statements are going to be removed

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1268]
It should be mentioned that the with statement is going to be removed in a future version and should therefore be avoided.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements#with-statements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8af30e-3d81-30c3-44c8-fc4cb631d001
* Version Independent ID: 315c1531-77aa-c602-6c0b-41d160d791e2
* Content: [AL Simple Statements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-al-simple-statements)
* Content Source: [dev-itpro/developer/devenv-al-simple-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-al-simple-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the feedback. With the current release and AL Language extension, the with statement is still supported. The docs first and foremost support the current version. And once the next major release is introduced, there will be a deprecation period for developers to rewrite their code. Usually this would not trigger a change or warning in the docs at this period. We have, however, inserted a note in the topic mentioned above as this is not the first request we got. The topic will be fixed with the next refresh of the docs. Thanks.
