### ISSUE TITLE
Translating other extensions

### ISSUE THREAD

**Issue by krregg** [MicrosoftDocs/dynamics365smb-devitpro-pb#1296]
I am following the information about translating other extensions, where the case is described for Base Application. I assume that it should work for any other extension also but no success. 

I created a new extension and I added a dependency on my custom extension which I want to translate and at the end I added .xlf files.

My app.json file looks like that (I tried to remove the dependency on Base and System Application and also nothing worked the same as if I use dependencies on them):

```
{
  "id": "54d78edb-03fb-40e5-aeca-ed086e1b11e4",
  "name": "Translations",
  "publisher": "Default",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "dependencies": [
    {
      "appId": "be9ee43a-9fc0-2e12-6cef-d8a5df09e355",
      "publisher": "Default",
      "name": "CustomApp",
      "version": "1.0.0.0"
    }
  ],
  "platform": "15.0.0.0",
  "showMyCode": false,
  "runtime": "4.0",
  "features": ["TranslationFile","GenerateCaptions"],
  "supportedLocales": ["sl-SI","pl-PL"]
}
```

Then I created a folder `Translations` in the root of the project and I added translated .xlf files. 
The content of the folder `Translations` in my `CustomApp` extension is only one CustomApp.g.xlf file generated by default when building CustomApp. 

The content of the folder `Translations` in my `Translation` extension is this:
```
Translation.g.xlf
CustomApp.sl-si.xlf
CustomApp.pl-pl.xlf
```

How should I name the files? Is this correct?

When I publish this nothing really happens. But if I include all translations in CustomApp then everything works fine. But that is not what I need, I want to separate translations from my CustomApp. How can I do that then? What am I missing here? 

I am using Business Central: Version: W1 15.1 (Platform 15.0.37898.0 + Application 14.0.29530.0)

I hope you can help me with that, thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translating-other-extensions)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by thpeder** [comment]
Hi @krregg,
As you have said, having another app with the translated files in, taking a dependency on your custom app, with the TranslationFile feature enabled should do the job.
One thing you can check is that in the translated files you will find a origin attribute, if that have the name of your translating app, then it will not apply the translations to the other apps. This hasn't been documented yet but will be added soon.

If that doesn't work then try to make two small apps that reproduces the issue and which you can share with us so we can look into the issue.

Note: Not all things are translatable in 15.1 as it was fixed in later versions, such as Enum Values. The majority of things can be translated, Page Actions, Page Controls, Table fields, Labels and so on. Please check with these first to know if it doesn't work in general or just for one case.

**Comment by krregg** [comment]
@thpeder thank you for your answer. 
I had to test a new version of Business Central 16.3 and at this point, I tried the same thing on a new version and it worked as expected. Somehow the same thing did not work in version 15.1. I also didn't try this on any other version so I guess something is not working well in version 15.1. But I think that is not the case anymore because the new version of BC is more relevant.

Anyway I made an example and I posted it here on Github if anyone needs to see an example: [github.com/krregg/bc-external-translations](https://github.com/krregg/bc-external-translations)
