### ISSUE TITLE
Need more info about permissions for assigning roles

### ISSUE THREAD

**Issue by bcraigie** [MicrosoftDocs/dynamics365smb-devitpro-pb#1297]
[Enter feedback here]
After creating a role and assigning it to a user, the user gets the error "You don't have permission to use the Role Centre [role center name]"

There should be some documentation about how to give the user the permission to use it.  Given that I've assigned the role to the user, the permission should have come with that assignment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baccd8df-f503-da27-3198-07aa5a5ea6ed
* Version Independent ID: 09faac4b-946c-956d-be75-469627ecc3b5
* Content: [Designing Role Centers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-role-centers)
* Content Source: [dev-itpro/developer/devenv-designing-role-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-designing-role-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by javariya** [comment]
Hi, 

The information regarding the issue is available at [Manage User Profiles](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-users-profiles-roles)
Specifically, in these sections of the article: 
[To define user settings for a profile](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-users-profiles-roles#to-define-user-settings-for-a-profile)
[To activate a profile](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-users-profiles-roles#to-activate-a-profile)

You can also refer to these articles:
[Assign Permissions to Users and Groups](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-define-granular-permissions)
[Create Users According to Licenses](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-users-permissions#licensespermissions)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your patience. We've added links to relevant topics. Available with the next doc refresh. Thanks.
