### ISSUE TITLE
No Documentation about unsupported Triggers in API Pages

### ISSUE THREAD

**Issue by ReneGubler** [MicrosoftDocs/dynamics365smb-devitpro-pb#1460]
There is no documentation which Triggers are not supported on Pages with "PageType = API".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0e36d7-395e-ed94-2e77-f7edb74e7757
* Version Independent ID: 1f838a73-fefc-8fbd-bcb9-cc9ad899dbdd
* Content: [Page and Action Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-page-and-action-triggers)
* Content Source: [dev-itpro/developer/triggers/devenv-page-and-action-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-page-and-action-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We have, since you filed this issue, been able to auto-generate the triggers from source code that are available in AL. These are grouped by object that they support. We do not have a more granular description than this. For the overview, please see https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/devenv-triggers. I suggest that for pages of the API type, you use IntelliSense to look up which ones are available.
