### ISSUE TITLE
Partial Records and Data Caching

### ISSUE THREAD

**Issue by gintuoklis** [MicrosoftDocs/dynamics365smb-devitpro-pb#1480]
Could you please explain how does partial records works with nav server data caching?
Will partial records, have it's own cache or you are using shared cache for full records?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c67b2cc-343c-b1ef-ed99-6eaf1a611548
* Version Independent ID: 32de46ff-68e9-b2f3-0aaa-e69cc79bb0ff
* Content: [Partial Records - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-partial-records)
* Content Source: [dev-itpro/developer/devenv-partial-records.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-partial-records.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by PhDuck** [comment]
Hey @gintuoklis,

I should preface this with the warning that it is an implementation detail that may change from version to version. So we will not give any guarantees about its behavior.

That being said, partial records are co-located in the same caches as normal records. Attempts to re-use cached results will be attempted against the same caches, with extra conditions regarding which fields are required.

As an example, doing a GET on a normal record first, followed by a GET on a partial record of the same type, may lead to using the first cached item with all fields, since the platform determined it faster to re-use than to go back down to SQL.

**Comment by jswymer** [comment]
Hello, We'll close this issue for now. If we haven't answered your question, please let us know and we'll reopen the issue. Thanks for the feedback!
