### ISSUE TITLE
how to get over 20000 entries ?

### ISSUE THREAD

**Issue by kinglomei** [MicrosoftDocs/dynamics365smb-devitpro-pb#1528]
For OData request limits, Max page size is set as 20,000 entities per page,
so how to get the rest entries(over 20000)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fc3b614-8a3a-0858-80e2-781b1b6e1253
* Version Independent ID: eabcadf6-051e-6631-f5d6-16ccdcef62a7
* Content: [Operation Limits in Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online)
* Content Source: [dev-itpro/administration/operational-limits-online.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/operational-limits-online.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,

If there are more than 20000 records in the queried result set, the OData response will contain a odata.nextlink with a $skiptoken to the next result set, where the $skiptoken  is assigned the key value of the last sent entity: For example:
​
`"@odata.nextLink":"http://myserver:7048/BC170/ODataV4/Company('CRONUS%20International%20Ltd.')/Customer?$skiptoken='01905893'"`
    
So if client receives a result which contains odata.nextlink, you can get next result set and repeat until there's no more nextLinks.

I hope this helps, otherwise, let us know.

**Comment by kinglomei** [comment]
Thanks for your reply.
$skiptoken works well.
Sorry my customers have the other questions about this limits:
1. It's right there are default or internal sort keys to make sure Web Service subscribers get same resultsets.
2. using $skiptoken can get more that 20000 entries, is it possible to get entries more flexibility?
    (such as 1st time to get top 5000 entries, then get next 5000 entries, then get next 5000 etc.)

**Comment by jswymer** [comment]
Hello,

Here is some info from the development team. I hope it helps.
 
1. If you want to ensure ordering for different clients, you can use the $orderby query parameter. Otherwise, the order is not guaranteed and is usually controlled by SQL server optimizations.

2. You can use following header in HTTP request to adjust the page size:  Prefer:odata.maxpagesize=5000.
