### ISSUE TITLE
What conditions other an invalid value cause this to be raised?

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-devitpro-pb#1690]
Documentation says 

> Property 'target' has invalid value.

But I use OnPrem which is a valid value and get the message

> App.json 'target' property must not be set to 'Internal' or 'OnPrem'.

Runtime is set to 6.0.

In general the documentation Code Analyzer rules is woefully vague, can this be improved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229e667b-0dcb-73b2-1311-baaaadd53d07
* Version Independent ID: ecb669bd-c320-c245-3e3a-07cab7caf2e8
* Content: [Property 'target' has invalid value. - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/pertenantextensioncop-pte0005-manifesttargetmustnotbeinternal)
* Content Source: [dev-itpro/developer/analyzers/pertenantextensioncop-pte0005-manifesttargetmustnotbeinternal.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/analyzers/pertenantextensioncop-pte0005-manifesttargetmustnotbeinternal.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. I am not sure what is causing this, because for runtime 6.0 - the value OnPrem should be perfectly valid. The message that you get doesn't use double-quotes, which is the right syntax - like this "target": "OnPrem", but compilation would catch that first. Other issues might be that the app doesn't publish to a local host, or that some other setting is contradictory to the OnPrem setting in the app.json file. Unless such a setting is causing the analyzer rule, I have to suggest that you contact support to get help on other factors which might cause this error. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing this topic
