### ISSUE TITLE
Wrong link from doc of FieldRef.SetFilter() to Record.SetFilter()

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-devitpro-pb#1757]
The text "_This method is like the SetFilter Method (Record) method._" has a link on "_SetFilter Method (Record)_" to this page:

* [Data Types and Methods in AL](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/library)

That's not useful. It should go where it says; that is, to

* [Record.SetFilter Method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/record/record-setfilter-method)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db588c54-dcb3-9b0b-a027-bc172fb38e2e
* Version Independent ID: 5606140a-8a79-0fce-0ee8-e8553c8cc62d
* Content: [FieldRef.SetFilter Method - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/fieldref/fieldref-setfilter-method)
* Content Source: [dev-itpro/developer/methods-auto/fieldref/fieldref-setfilter-method.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/fieldref/fieldref-setfilter-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by dtkb** [comment]
Saying that, isn't it weird that the FieldRef doc has way more info than the Record version? Since the latter is more fundamental, I'd think the bulk of the info should go there. Either way, the one with less info should link to the one with more info... and currently the opposite is the case, i.e. the Record doc doesn't link to the FieldRef one, which is more detailed. :-S
