### ISSUE TITLE
Some Property Values not Supported with 1.0

### ISSUE THREAD

**Issue by mjmatthiesen** [MicrosoftDocs/dynamics365smb-devitpro-pb#1763]
I think this article would benefit from granularity. TableType=Temp is not supported until runtime 6.0, despite what the article says at the top (1.0). I realize that is likely for the property itself, but clarification in the values would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ce6f5a-62dc-0bf3-621f-078ccba5f844
* Version Independent ID: 5ebef0bb-97c2-dd79-7ad0-03633c97494c
* Content: [TableType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-tabletype-property)
* Content Source: [dev-itpro/developer/properties/devenv-tabletype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-tabletype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. This topic is auto-generated from the source code in order to reflect more accurately as opposed to maintaining these topics by hand, which can be error-prone and very time consuming. This leads to a more generic handling, such as this case, where the property is introduced in an early version, but updated for support later. To fix this, we would have to do a tools update. I think that you get an error if you try to use the Temp table type in the compiler, if I am not mistaken?
I will add a task on our backlog to look into if there is an inexpensive fix in the code to add this support. Thanks.
