### ISSUE TITLE
Recommended content on this topic does not make sense

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-devitpro-pb#1784]
Have a look:

![image](https://user-images.githubusercontent.com/18466198/113473253-c6568280-9468-11eb-82ca-5bba92da2bc2.png)

BTW: this seems to be a relatively new feature. What is the logic behind how these topics are picked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9a88b1-f7e9-e4cb-6b06-4d9e11ef4e35
* Version Independent ID: c9b7c384-2643-75e6-c9cd-308d3b77042f
* Content: [TestPermissions Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-testpermissions-property)
* Content Source: [dev-itpro/developer/properties/devenv-testpermissions-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-testpermissions-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by edupont04** [comment]
Hi Luc,
The links in the Recommended Content section are automatically generated based on usage of the content.  We don't control it in any way. Over time, the links might make more sense, but right now, because this property article is often read at the same time as the docs for a couple of other properties, they are seen as related.

Closing as related to the docs.microsoft.com site and not particular to the Business Central docs.

**Comment by lvanvugt** [comment]
Hi Eva,

Just what I thought nevertheless it seems very useless right now, and actually to me annoying. Maybe the responsible team can put some tip/info so I as user know why this is?
