### ISSUE TITLE
Tag for BC 18?

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#1786]
As I have learned on [Twitter](https://twitter.com/KarolakNatalie/status/1367460762516680705?s=20), this article should mention that we can use this feature from BC 18 on (at least in the cloud). 
However, the article also mentions the Barcode module in the System App which in fact is available already earlier than in BC 18.
That's why I was not confident enough to create a pull request for this article myself ....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04fb2aaa-8676-c0ae-434b-eb3d85bddca4
* Version Independent ID: 9d634195-090b-8b48-1059-e45233d7dcba
* Content: [Adding barcodes to reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-add-barcodes)
* Content Source: [dev-itpro/developer/devenv-report-add-barcodes.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-report-add-barcodes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, good points! This s

**Comment by jswymer** [comment]
Hello, thanks for the valuable feedback.

This feature applies to BC 2021 release wave 1 (v18) and later, for both online and on-premises. As for on-premises, it's first introduced as part of the System Application in version 18.

We've updated the article to indicate that it applies to v18 and later. The update will be published soon. We hope this helps,  otherwise, let us know and we'll reopen this issue.

Thanks again!
