### ISSUE TITLE
How do I format an integer to have comma for thousands?

### ISSUE THREAD

**Issue by grantbrimhall** [MicrosoftDocs/dynamics365smb-devitpro-pb#1863]
This page has a lot of information. But doesn't answer the simple question of how to format the integer 1234 as 1,234.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 469a62c8-2505-8533-a1b6-d9f4d27f59b4
* Version Independent ID: fa107bb8-b17b-c938-e17c-6a67e7faa19b
* Content: [Formatting the Data in a Field - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-format-field-data)
* Content Source: [dev-itpro/developer/devenv-format-field-data.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-format-field-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. The thousand separator depends on the regional setting that you have in Business Central. This must be US to be displayed as a comma (instead of a period when it's set to Danish). For example this line of code:
Message(Text000, Format(-1234, 12, '<Integer Thousand>')); - will display as 1.234 with regional settings for Danish, and 1,234 as regional settings for US. Thanks

**Comment by SusanneWindfeldPedersen** [comment]
Hello, I think this issue was addressed through a previous issue, so closing this now.
