### ISSUE TITLE
Link to download YML is broken

### ISSUE THREAD

**Issue by skkulla** [MicrosoftDocs/dynamics365smb-devitpro-pb#1905]
Link to download YML is broken. How can we get YML for version 2.0 ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3f68316-e01d-f777-6992-40c61ceace15
* Version Independent ID: 0d15da82-fb45-3d49-dfd8-e40913122bdc
* Content: [(v1.0) 'OpenAPI Specification' - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v1.0/dynamics-open-api#previewing-the-openapi-contract)
* Content Source: [dev-itpro/api-reference/v1.0/dynamics-open-api.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/api-reference/v1.0/dynamics-open-api.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for catching this. The link to download v1.0 will be fixed with the next doc refresh. For version 2.0 we're looking into if we can provide a yaml file in the same manner. If you, however, want to move on with this we recommend that you take a look at the [OData metadata conversion to OpenAPI specification on Github](https://github.com/microsoft/OpenAPI.NET.OData). Using that, you will have a starting point for the OpenAPI specification. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing for now, having v2.0 work on the backlog. Thanks.
