### ISSUE TITLE
Error in section On-Premise deployment - Online library

### ISSUE THREAD

**Issue by JuricaB** [MicrosoftDocs/dynamics365smb-devitpro-pb#207]
In example in this section, comment sections (starting with "//... ) must end with comma. 
Copy/pasting example as-is will crash Web client on start.
Also - the last line should only have a comma at the end if you paste it to beginning of the file. 
Lastly, if using Online Help while on-prem, you need to clear HelpServer key. This is not clear from the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61d22259-29ef-f2d9-2313-e9e81db5090e
* Version Independent ID: e0838e47-03b9-a0c8-67bc-85eb3668d527
* Content: [Help setup - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-help)
* Content Source: [dev-itpro/deployment/configure-help.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/deployment/configure-help.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi, thanks for catching this issue! I'll get this clarified by the end of the week.
It's always problematic with these snippets for the configuration files because the files are formatted in a way that makes them difficult to scan and modify unless you have a large monitor. I prefer to delete the comments because that makes the JSON easier to scan, which is why this copy-paste mistake occurred.

Again, thanks for catching it!

**Comment by edupont04** [comment]
The content has been updated, so I'm closing the issue.
