### ISSUE TITLE
Migration subsequent runs

### ISSUE THREAD

**Issue by gm-vas** [MicrosoftDocs/dynamics365smb-devitpro-pb#2114]
Hi!

Description for "Run Migration Now" action mentions that "...The migration can also be used for subsequent runs after the initial migration. On subsequent runs, the migration tool will only migrate changes that have happened since the previous migration was run. Change tracking is used to identify what data should be moved in those subsequent runs."

But in current version of BC (Platform Version 19.0, Application Version 19.0.29894.30403), after first successful migration, when you run Action "Run Migration Now" an error is shown: "Cloud migration can't be run, because an upgrade has started on company XXXXXX (upgrade status: Completed). Either exclude the company from migration or delete it, then try migration again.". 

Does this mean, that subsequent runs are not possible in BC 19 Online?

Thanks!

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You're right that the wording is misleading. This will be fixed in the next doc update.

Essentially, in version 19, the migration of data is separated from the upgrade to the latest version. You can run the migration multiple times, but once you choose the Upgrade action, you cannot migrate more data.

**Comment by edupont04** [comment]
Now fixed.

**Comment by gm-vas** [comment]
Thanks a lot!
