### ISSUE TITLE
Errors on multitenant

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-devitpro-pb#221]
First of all, small typo in documentation. The Sync-Navtenant is written as "Set-NAVTenant -ServerInstance &lt;ServerInstanceName&gt; -Tenant &lt;TenantID&gt;"

However, when I try to upgrade my 2018 CU2 tenant I get error:
Invalid column name 'Schema Hash'.
Statement(s) could not be prepared.

It seems that this column does not exist in Object Metadata Snapshot in my tenant database.

Steps in my process:
Upgraded tenant from 2013R2 to 2018 CU2
Dismount tenant from 2018
Mount tenant on BC
Sync-Navtenant - results in error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dde0890-47c3-1cfb-761b-321fe39f9e21
* Version Independent ID: de7dad4e-83a0-4a02-8caa-bde1187396c4
* Content: [Upgrading the Database - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data-multitenant)
* Content Source: [dev-itpro/upgrade/Upgrading-the-Data-Multitenant.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/Upgrading-the-Data-Multitenant.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback. I fixed the typo for the Sync-NAVTenant. As for as the sync error, I have contacted  jthe development team to provide some insight. If you can provide more information about your scenario, what you did, and errors, that would be great.

**Comment by ERPgruppenMW** [comment]
Thanks for quick reply.
My steps more detailed:
Upgraded 2013R2 tenant by:
uploading new 2018 license to tenant db, dismount from 2013R2 and mount in 2018 cu2 running multi tenant server instance with upgrade toolkit in app dB
Sync-navtenant on tenant
Adding own dev user and test everything looked fine
Removing upgrade toolkit, sync-navtenant
Dismount tenant

On BC:
Mount tenant on running BC server instance with upgrade toolkit in app dB
Sync-navtenant. Here comes error.

Problem seems to be, that we have an old version of database on 2018 tenant. But I cannot find out where/what step tenant database should be updated

Do you have any idea oh when we find a solution?
My idea was to import app in tenant dB, and try BC upgrade as single tenant solution. But that seems like a more time consuming way to approach this.

Thanks


Med venlig hilsen
Mads Westen

________________________________
Fra: jswymer <notifications@github.com>
Sendt: fredag, november 2, 2018 9:45 AM
Til: MicrosoftDocs/dynamics365smb-devitpro-pb
Cc: Mads Westen; Author
Emne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] Errors on multitenant (#221)


Thanks for the feedback. I fixed the typo for the Sync-NAVTenant. As for as the sync error, I have contacted jthe development team to provide some insight. If you can provide more information about your scenario, what you did, and errors, that would be great.

**Comment by jswymer** [comment]
Thanks. I passed the info on.

**Comment by ERPgruppenMW** [comment]
Any news on this topic yet? Sitting with a customer who wants to move data to BC Cloud solution. Wanting to use Intelligent Edge to push data once tenant is upgraded...

**Comment by jswymer** [comment]
Sorry but there is no update on this yet. I recommend that you escalate this as an issue through the CSS/support channel. This will give better tracking and raise the importance. Regards.

**Comment by ERPgruppenMW** [comment]
Hi,

Sorry to ask, but what do you mean with CSS support? Our Partner support through Partner Source?

Med venlig hilsen / Kind regards

Mads Westen

Direktør/Manager, ERPgruppen Kolding |D: + 45 78 79 41 51 | mw@erpgruppen.dk

[ERPgruppen]<http://www.erpgruppen.dk/>

Hovednr.
Support
Website

+ 45 78 79 40 40
+ 45 70 70 70 66
www.erpgruppen.dk

ERPgruppen
Kolding, Aarhus, Horsens, Slagelse, Hellerup
Læs mere om ERPgruppen her<http://erpgruppen.dk/profil/>

Få support på C5, NAV, Dynamics 365 og Stackss - man.-tors. kl. 8.00 - 22.00 (fre. til kl. 15.00)     [Få hurtig hjælp fra supportafdelingen]


[Tilmeld dig gratis seminar om Dynamics 365 & Office 365]<https://t.xink.io/Tracking/Index/w8EBAM8rAADFQAUA0>

Fra: jswymer [mailto:notifications@github.com]
Sendt: 6. november 2018 09:08
Til: MicrosoftDocs/dynamics365smb-devitpro-pb <dynamics365smb-devitpro-pb@noreply.github.com>
Cc: Mads Westen <mw@erpgruppen.dk>; Author <author@noreply.github.com>
Emne: Re: [MicrosoftDocs/dynamics365smb-devitpro-pb] Errors on multitenant (#221)


Sorry but there is no update on this yet. I recommend that you escalate this as an issue through the CSS/support channel. This will give better tracking and raise the importance. Regards.

**Comment by jswymer** [comment]
This communication thread has been continued outside of GitHub issues. If the resolution of this issue requires documentation updates, we will make the updates. Thanks for the feedback.

**Comment by ekesteloot** [comment]
Hello,

I am experiencing this issue upgrading a tenant from NAV2018CU09 to BC_CU01.  @jswymer you mentioned that this thread has been continued elsewhere.  Can you point me to the resolution?

Thank you!

**Comment by wisa1** [comment]
Same issue here, although half a year later. Would really appreciate if issues would be resolved by actually posting the solution :(

**Comment by ERPgruppenMW** [comment]
@wisa1 do you have the problem about "Invalid column name 'Schema Hash'."?
I am not completely sure about the detailed steps, but it seems you must install an extension on 2018 before moving to BC. Just install and uninstall again, as the upgrade tells you to.
It is my belief that installing the extension will create extra column or prepare creation...

**Comment by wisa1** [comment]
@ERPgruppenMW yes i had the problem with the 'Schema Hash' column. However since i got stuck there, i just ended up throwing the half-upgraded database into the trash and started from a fresh 2018 DB again. This - for some reason - fixed the issue, and the upgrade went as planned. NAV/BC sometimes works in mysterious ways.

I really appreciate you taking the time to comment on a half year old thread to help out a stranger, thank you.

**Comment by jswymer** [comment]
Yes, thanks for contributing. Unfortunately, the writers have not yet gotten any clear directions about the exact cause of this issue. 

However, in short, if you experience this issue, you can try to fix it by running a technical upgrade on the NAV application and tenant database according to the guidelines in [this article](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/converting-a-database). When completed, you should be able to mount the tenant on the Business Central application, and then run sync-navtenant.

The Schema Hash column was introduced to the Schema Metadata table of the application database when we released Business Central April 2018. You get this error because the tenant database has not gone through a technical upgrade (conversion) to bring it to the new platform. The technical upgrade adds the Schema Hash column to the tenant’s Object Metadata Snapshot table. The technical upgrade should be initiated by the Sync-NAVTenant cmdlet. But for some reason, this is not happening in some scenarios. This might be an issue with the application that you are mounting the tenant against. For example, things seem to work if you upgrade your NAV application to Business Central by doing a compare-merge as described in [this article](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-application-code). However, if you just try to mount the NAV tenant database against the Business Central Demo application, the tenant technical upgrade is skipped, and you get the error.

It would be interesting to hear more about the application that you are mounting against

**Comment by ERPgruppenMW** [comment]
But what if you only want to upgrade 1 tenant and thereby not entire multitenant solution. You would have following scenario:
A: NAV 201x multitenant server running multiple tenants
B: BC Cloud
C: Customer running as tenant on A

Now C want to move from A to B. The rest of tenants on A are not ready to move. What would be best approach on this?

**Comment by jswymer** [comment]
Sorry, I think I need to better understand your scenario. Is  "BC Cloud" on Business Central Online solution or an on-premise installation of Business Central?

**Comment by ERPgruppenMW** [comment]
BC Cloud is SaaS / Online and not On Premise.

**Comment by jswymer** [comment]
Ok, thanks. If it is a BC cloud solution, then I assume you do not have direct access to manage it, correct? So are you working in a Sandbox environment?

**Comment by ERPgruppenMW** [comment]
Correct, direct access to manage it. Sandbox is possible (although I have not testet Intelligent Cloud possibility to a Sandbox). But Sandbox is not that important since in my process, the BC tenant will only have Cronus data.

**Comment by jswymer** [comment]
A workaround for this if you only want to upgrade 1 tenant and thereby not entire multitenant solution is: 

1. Add the NAV Application to the tenant database. For example, from the NAV Development Shell, run:
Export-NAVApplication -DatabaseServer <databaseserver\instance> -DatabaseName <NAV 2018 Application DB> -DestinationDatabaseName <Tenant DB>
2.	Using Development Environment (CSIDE) installed with Business Central, open and convert the tenant database. This should add the Schema Hash column.
3.	Remove the Application from the converted tenant database:
Remove-NAVApplication -DatabaseServer <databaseserver\instance> -DatabaseName <Tenant DB>
4.	Mount the tenant to the Business Central 130 Server instance.
5.	Run sync-navtenant.
6.	Run start-NAVDataUpgrade.
