### ISSUE TITLE
Instruction #4 seems unclear

### ISSUE THREAD

**Issue by moyacarousel** [MicrosoftDocs/dynamics365smb-devitpro-pb#228]
I followed the instructions on this page until #4, which seems unclear. "In Dynamics NAV" seems ambiguous in this context. Does this mean in the Dynamics NAV client? Or within the Dynamics NAV instance under the Console Root of the Admin tool that we were already working in? Also, "search for API Setup" isn't clear. Where is the search feature to use? The search feature in the Dynamics NAV client doesn't yield any results for the API Setup, and I can't see a search feature in the admin tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e91e4d8-5e4e-80a4-0e46-e2d23fc83155
* Version Independent ID: 07a13af1-543c-f8de-0daa-6fd2cc27cea0
* Content: [Enabling APIs for Microsoft Dynamics NAV - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/enabling-apis-for-dynamics-nav)
* Content Source: [dynamics-nav/enabling-apis-for-dynamics-nav.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/enabling-apis-for-dynamics-nav.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hi, thanks for the feedback. I agree this topic is confusing, probably primarily because of branding. The product name should be Dynamics 365 Business Central on-premises. And you should be able to search for the API setup page in Business Central, using for example the web client - look for the light bulb and then enter "API setup". Hope this helps. I will update the topic accordingly. Thanks.

**Comment by moyacarousel** [comment]
Those details are great, and help make the instruction much more clear. Thank you!
