### ISSUE TITLE
Business Central: Creating Filter Pages for Filtering Tables - Bad Code Example

### ISSUE THREAD

**Issue by cstuber** [MicrosoftDocs/dynamics365smb-devitpro-pb#2297]
The given example is not very good regarding style.

- Usage of variable prefixes "var"
- Hard coded text where translatable labels or build in table- and fieldcaption should be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db8eed29-21d3-3273-f8af-09b8008c6b54
* Version Independent ID: 11a51cb3-c782-0140-c2e3-f89a0d903770
* Content: [Creating Filter Pages for Filtering Tables - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-filter-pages-for-filtering-tables)
* Content Source: [dev-itpro/developer/devenv-filter-pages-for-filtering-tables.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-filter-pages-for-filtering-tables.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by dnpb** [comment]
The `.Add*()` calls can and perhaps should use non-translateable strings, since those are names by which tables/fields can be referenced later, possibly by other code running as a different language. The `PageCaption` indeed should use a translatable label though.

The `var` prefixes indeed are unnecessary and misleading. Even though e.g. `FilterPageBuilder` as a name will get syntax-highlighted as if it were the type, that still works and builds. I used to quote such identifiers but have gotten too tired to bother

**Comment by cstuber** [comment]
Even for the `Add` functions I would use `TableName()` and `FieldName()`. Too many hours of debugging were wasted to find out that someone made a typo in a string.

**Comment by jswymer** [comment]
Thanks for the feedback. We made some changes to the article based on the suggestions. The update will be published soon.
