### ISSUE TITLE
Mismatching and vague documentation

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-devitpro-pb#2298]
Hi,

We have a bigger prospect with >400 users for which we would like to do a performance evaluation.
It is with this perspective that I'm reading this documentation.

In the[ Sandbox section](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/environment-types#sandbox-environments) it states:
"_You can create a sandbox environment that includes data from your production environment for debugging purposes, for example. But if you want to run performance tests, or similar benchmarking, the sandbox is not reliable enough for that purpose. This is because sandboxes run in a different performance tier on Azure than production environments. Instead, create a dedicated environment based on the Production environment type - this gives you the exact experience and performance that users will experience in the actual production environment._"

Further in the [Pre-sales performance evaluation](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/environment-types#pre-sales-performance-evaluation) section it states:
"_To demonstrate the functionality of the service, with a focus on performance, you can take the same step as outlined above, but then also sign up the prospect for the Business Central Premium Trial offer that is available through your CSP access in the Partner Center, wait 24 hours, and then run your performance evaluation. For more information, see [Preparing Test Environments of Dynamics 365 Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/test-environment)._"

I'm missing the information on HOW we should do the performance evaulation. Do we need to educate >400 users and then make them run test cases or is it a tool for this? It says see "Preparing Test Enverionments.." for more information but there is not a single word of performance there so that doesn't help.
I know from other sources that there is a performance toolkit BUT it can ONLY be run on sandboxes which previously stated isn't an option.

It also says "For more information about performance and Business Central, see [Performance Overview](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/performance/performance-overview)" but I can't see any answers there to that question either :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a95f13c8-fb95-973a-6a59-d1289031a9d3
* Version Independent ID: 878a96a5-dd68-542a-82af-d46a461c5916
* Content: [Production and Sandbox Environments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/environment-types#production-environments)
* Content Source: [dev-itpro/administration/environment-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/environment-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hej Marcus,
We don't provide guidance for how to run performance tests, because that depends on the concrete solution that you want to test - and the purpose of the test. For example, you might want to test if a tenant in a particular Azure region can process a high number of transactions, or if multiple users can post documents at the same time from the Outlook add-in. If your need for performance tests is for pre-sales, meaning being able to tell prospects that "sure, you can run your core scenarios just fine in the cloud", then it's one thing. If the test is to identify problems with your own code, it's another scenario.

As for sandboxes, they are highly useful for most scenarios, but not for enduser performance because, on the backend, they are given fewer resources than the production environments. The [Performance Toolkit extension](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-performance-toolkit) is intended for development environments so that you test a solution before you ship it. Theoretically, you could run it in a production environment or sandbox environment, but as the docs for it say, the toolkit's intended for sandboxes because it's intended for development scenarios. So it would be a performance test of the _code_, not a test for what the actual experience in production is going to be like. Again, production environments are better for evaluate what the user experience is going to be like - and then you can tweak that with dfferent browsers, different internet speeds, and so on.

I hope this helps you. Otherwise, do let us know.

**Comment by edupont04** [comment]
Closing as answered.
