### ISSUE TITLE
Add more detail on how fields are populated for GDAP users

### ISSUE THREAD

**Issue by RafaelKoch** [MicrosoftDocs/dynamics365smb-devitpro-pb#2422]
Suggesting to add more detail: On table `User` the  field `Authentication Email` gets populated with the delegated admins company name, followed by `Technician`. And the `contact email` field will be populated with a unique ID in the following format `[User123456@partnerdomain.com](mailto:User123456@partnerdomain.com]`

Reason for this suggestion: This is quite unusual design and we experienced unexpected runtime issues with our first GDAP instances because of conflicting app code. One does expect an email adress in a field called "whatever email"...  so some clarification what to expect is probably a good idea.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66412cff-bccf-0553-ad97-7bb9ea6c63a9
* Version Independent ID: 6d046b65-1832-bf77-6eec-3d8350f4d83e
* Content: [Delegated admin access to Business Central online - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/delegated-admin)
* Content Source: [dev-itpro/administration/delegated-admin.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/delegated-admin.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Tobias,

If you find that GDAP causes problems in the product, please reach out to the usual support channels. GDAP as a concept is explained here: https://docs.microsoft.com/partner-center/gdap-introduction

If a partner switches to GDAP, then users from their company are still shown in the Users list in BC, but not with their actual names and email addresses. That is helpful for GDPR reasons, not least.

Our current wording in the BC article says the following:

"GDAP users are listed with user names in the following format: User123456@partnerdomain.com. They might have **a user name that reflects the partner's company name, and the email address is not the person's actual email address**. This way, the GDAP user accounts do not reveal personal information. If you need to find out who the person behind such a pseudonym is, you'll have to reach out to the company that this user works or worked for."

That wording covers the experience (I've highlighted the existing words that I believe you're looking for). We've also added tips for how the partner can maintain a list internally of who has ever worked with which customer, though we prefer to leave best practices to you guys, since you obviously all have different best practices already.

Closing the Issue.
