### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by DavidCurd** [MicrosoftDocs/dynamics365smb-devitpro-pb#2436]
The link to https://go.microsoft.com/fwlink/?LinkID=510894 doesn't work:

Hmmm… can't reach this pageCheck if there is a typo in mbs.microsoft.com.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30dd402-c112-00be-9c66-4f8bd6a2184f
* Version Independent ID: 215be880-512c-a76b-5463-bfd1b349dd81
* Content: [Microsoft Dynamics 365 Business Central Server Configuration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configure-server-instance#ODataServices)
* Content Source: [dev-itpro/administration/configure-server-instance.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/configure-server-instance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! The link is broken because it was supposed to go to the readiness library for Dynamics NAV 2015, which no longer exists. Instead, you can take a look at this article: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/authenticate-web-services-using-oauth

The link will be fixed in the next doc update.
