### ISSUE TITLE
Upgrade Steps - Task 12 - Reinstall Apps

### ISSUE THREAD

**Issue by JeremyVyska** [MicrosoftDocs/dynamics365smb-devitpro-pb#2458]
I had someone trying to follow the guide to see if they could upgrade a BC19 to 20.

On Task 12 (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v20#task-12-reinstall-extensions-single-tenant-only), the way it's written, this reads that you should just reinstall the Apps as before.

But, for the BC 'standard' apps, there's a whole list of ones that are new/upgraded every major.

Shouldn't this Task break that out into:
 - Reinstall existing 3rd party extensions (or upgrade per their instructions)
 - Upgrading the Microsoft Base Extensions provided in the \Applications folder

You could just name a common/core one as an example for the \Applications folder, not spelling out each one, allowing the installer to evaluate the options.

But following advice as written could cause problems, I'd think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e817d25-cdd9-def2-7f49-b0cc6a5a6349
* Version Independent ID: 4e817d25-cdd9-def2-7f49-b0cc6a5a6349
* Content: [Technical Upgrade to Version 20 - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-technical-upgrade-v20)
* Content Source: [dev-itpro/upgrade/upgrade-technical-upgrade-v20.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/upgrade/upgrade-technical-upgrade-v20.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hi, thanks for the feedback!

Please excuse me if I am misunderstanding something. This article should only be used when you just want to upgrade to the new platform, not the application/extensions. In this case, you run the Task 9: Recompile published extensions to compile the old extensions (that is, the extensions from the previous version which are still published) so that that work on the new platform. Then, you reinstall the same versions later in the procedure.

If you want to use the new extension versions found in the  **\Applications** folder of the version 20 DVD, then you should use this article [Upgrading Microsoft System and Base Application to Version 20](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-to-v20).

I hope this helps, or let me know what you think. 

Regards

**Comment by JeremyVyska** [comment]
Ah, gotcha, was working from the wrong doc page then - yup!  Closing this one up.

Btw, your team's hard work on #1676 made doing so many of the upgrade steps a breeze and it was wonderful.

**Comment by jswymer** [comment]
Thanks! Glad you like the change done under 1676. It's good to hear that we are making some valuable improvements.
