### ISSUE TITLE
Additional step to finish task #2

### ISSUE THREAD

**Issue by v3ux** [MicrosoftDocs/dynamics365smb-devitpro-pb#2491]
[Enter feedback here]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/automation-apis-using-s2s-authentication#task-2-set-up-the-azure-ad-application-in-

This step would fail when a proper redirect URL isn't provided. 

The provided URL is https://businesscentral.dynamics.com/OAuthLanding.htm

It has been covered in https://www.kauffmann.nl/2020/09/14/service-to-service-authentication-for-automation-apis-in-business-central/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1555e693-76e8-b1d9-267f-bf06f068c9f4
* Version Independent ID: 725078be-b4d2-ced1-1ce0-52fc379f6a4e
* Content: [Using Service to Service Authentication - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/automation-apis-using-s2s-authentication)
* Content Source: [dev-itpro/administration/automation-apis-using-s2s-authentication.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/administration/automation-apis-using-s2s-authentication.md)
* Service: **dynamics365-business-central**
* GitHub Login: @henrikwh
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, thanks for the feedback!

Good catch. The article was incorrect. 

The issue is that you can grant admin consent from either the Azure portal or from the Business Central web client (by using the **Grant Consent** action). However, if you do it from the web client, you have to configure the redirect URL in the app registration. If you grant consent in the Azure portal, you don't have to provide the redirect URL and you also skip task 2, step 7.

We've changed the article to make this more clear. The update will be published soon.

**Comment by v3ux** [comment]
I'm pretty sure I had already tried the Grant Consent from the Azure Portal too (it would shoe Granted for Contoso), and of course along with the correct API permission assigned, before finding that missing redirect url from blog. Still, Publishing to Environment with Al-Go will always end up failing with error 401 unauthorized.

After I added that redirect, tried to grant consent again from BC, then publishing to environment worked correctly only that time, error arised from missing "D365 Ext. Management" for the user, but API was authorized (it can listed the installed extensions and so on).

I know it sounds odd and you might not believe it, but it's what happened to me.
