### ISSUE TITLE
But what about formatting

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#2539]
The doc says `When developing layouts for document reports, we recommend that you design Word layouts instead of RDL. `
But Business Central specifically does not support Word's field data formatting syntax, which is essential to layout formatting. Does this amount to Microsoft saying "we recommend that you not do any field data formatting in your layout, but instead do it in the report code itself?" Doesn't that severely limit the possibilities for user-modifiable customizations to a report layout?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 185e15dd-e5ae-2272-7d29-3207bdd08089
* Version Independent ID: dc0cdfd9-7480-6cc4-8c9e-db6ac05f2f6c
* Content: [Report Design Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-design-overview)
* Content Source: [dev-itpro/developer/devenv-report-design-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-report-design-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by nhsejth** [comment]
It's correct that we recommend using Word based layouts for document reports as RDLC based layouts are very hard to maintain for most users. 
During Word file rendering we do not modify the normal Word controls but will only modify the content controls bound to the xml elements in the custom xml that is stored in the document.
Formatting data should always take place in the report object itself to ensure coherent output disregarding system setup on the end-users computer, this is in particular relevant for data and number formats that can depend on the language settings in the BC environment.
This is not the same as saying that you cannot use standard Word controls, but it will not always be possible to embed xml content controls inside standard controls.
Notice that the page number controls are a bit special as they are controlled by the report rendering engine in order to support correct section page numbers when you print multiple documents in one batch resulting in one Word or pdf file.

**Comment by buzzwick** [comment]
It is very true that “RDLC based layouts are very hard to maintain for most users.” But it is also true that extensive layout-based formatting capabilities, which have become easy and familiar after so many years of using Report Builder and Visual Studio with NAV reports, are now lost to the developer. This inevitably requires significant extra work on the part of the developer, and means that minor formatting changes in a Word layout require developer intervention and coding. Layout-based visual designers are infinitely more capable, flexible, and efficient (change the number of decimal places on an entire table of data cells at once), not to mention easier to work with. (That said, I will certainly grant that the formatting control syntax in a Word layout is not exactly intuitive).

Such is life. Product design decisions are made, we have to live with them. Fine. But at the very least, perhaps Microsoft could make it a little more obvious in its documentation that formatting changes we have all come to expect to make in the report layout are no longer available.

**Comment by nhsejth** [comment]
Notice that it's a recommendation to use Word based layouts, it's not a requirement and we are not going to remove the rdlc option. So, partners and users that prefer rdc layouts can continue to use them, but our base document reports will be based on Word layouts (actually a transition that started about 10 years ago).

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. We will close this issue.
