### ISSUE TITLE
NavApp is NOT a data type

### ISSUE THREAD

**Issue by JMA1972** [MicrosoftDocs/dynamics365smb-devitpro-pb#2589]
In my opinion the complete section about NavApp is wrongly placed in the documentation, because NavApp gives us a system integrated set of functions but it is clearly not a data type. You can't declare a variable or a field with the type "NavApp" so it doesn't belong here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 998cf0ad-ecb7-fb94-2cc1-ba52fba6ca0e
* Version Independent ID: 4af5810a-9f8a-fec4-ab41-7193f11716c3
* Content: [NavApp Data Type - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/navapp/navapp-data-type)
* Content Source: [dev-itpro/developer/methods-auto/navapp/navapp-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/methods-auto/navapp/navapp-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for the feedback. The data types and their methods are auto-generated from source code. This includes the NavApp type. I agree with you on the definition, but we are most likely not going to take it out from the section because it would take modifications to our tooling and we'd have to find another home for it. But your feedback is appreciated. Thanks.
