### ISSUE TITLE
Missing information on related error and start enforcement

### ISSUE THREAD

**Issue by PeterBizz** [MicrosoftDocs/dynamics365smb-devitpro-pb#2594]
- What will be the error message when a non compliant dll is used ? 
- when will the error be generated? ( compile / install / run-time) 
- As of what version of BC onPrem is this behaviour enforced ( seems not to be active in v. 21.0.43576.0 version, since I can call and use .net variables residing in .NET framework compiled/targeted  dll )

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Version Independent ID: 1bd94618-808b-ebda-96d8-bcf0d41ccfda
* Content: [Migrating from .NET Framework to .NET Standard - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard)
* Content Source: [dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-migrate-from-dotnet-framework-to-dotnet-standard.md)
* Service: **dynamics365-business-central**
* GitHub Login: @KennieNP
* Microsoft Alias: **kepontop**

**Comment by jswymer** [comment]
Hello,

Because of .NET Compatibility Mode, using an assembly built for an old .NET Framework doesn’t result in any warnings or errors right now. That is, no errors will occur during compilation, installation, or calling the .NET add that targets an old .NET Framework. Read more about .NET Compatibility Mode here [Analyze dependencies to port code - .NET Core](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fcore%2Fporting%2Fthird-party-deps%23net-framework-compatibility-mode&data=05%7C01%7Cjswymer%40microsoft.com%7C2e828519529740f6761c08dac63f16f2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638040271558519252%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3G8S8gqRCSqYFyNiphuv%2FvCKy%2BYJS86P4FbdYUWxCAE%3D&reserved=0).

However, starting in Business Central 2023 release wave 1 (v.22), if a .NET add-in calls an API that isn’t supported by the .NET Standard runtime, it will generate an exception. This means that, theoretically, add-ins compiled for old .NET Framework can still work if they only use compatible .NET APIs.

We hope this helps. We will also make this clearer in the article.

Thanks for the feedback!
