### ISSUE TITLE
List of Global Events

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-devitpro-pb#269]
Our Developers License does not allow us to view the Global Event Codeunits 2000000001..2000000010. In this documentation there are no Events mentioned and VSCode does not Show the Events available. 

How are we supposed to know which Global Events to use? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 256aabb4-8d5d-cc06-6c1f-5558c668491b
* Version Independent ID: 51d1427c-130d-b5c0-3d04-89c01caa89f8
* Content: [Event Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-event-types#global-events)
* Content Source: [dev-itpro/developer/devenv-event-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-event-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback. Yes, your license prohibits you from viewing these codeunits. The reason is that we recommend that code does not subscribe directly to the events in these codeunits. Instead, the events are also published from various base application codeunits, like codeunit 40 and 43, as outlined in the article [Mapping Codeunit 1 method triggers to events](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/transition-from-codeunit1#mapping-codeunit-1-method-triggers-to-events).  Let me know if this helps. Thanks!

**Comment by JulianTillmann** [comment]
Please update the General Info About System Events on the Event page. I would argue that it's not an upgrade issue but a General one for all Integration.

**Comment by jswymer** [comment]
Hi Julian, I agree. We have some work scheduled in the near future to document these events and other methods in the base application codeunits. In the meantime, we have updated the article with a list of the global events. This update will be published soon. Thanks for the valuable feedback!
