### ISSUE TITLE
Upgrade only?

### ISSUE THREAD

**Issue by DavidCurd** [MicrosoftDocs/dynamics365smb-devitpro-pb#28]
Are technical upgrades supported only as part of an upgrade, or is it ok to a technical upgrade of a production database, after testing etc? This always used to be ok pre-RTC, but I was under the impression that was no longer the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221f01d5-21a5-b244-e419-f83ed74f84eb
* Version Independent ID: 3327eb70-9edb-cd5b-e935-ccb5c3008d7f
* Content: [Converting a Database - Technical Upgrade - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/converting-a-database)
* Content Source: [dynamics-nav/Converting-a-Database.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Converting-a-Database.md)
* Service: **unspecified**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello David,

I spoke with the dev team about this. Although the primary use is for "upgrade" scenarios, we have not blocked the possibility to run the technical upgrade in the scenario that you describe. You just have to  remember to synchronize your tenants after performing a technical upgrade. Also, take care not to change the application version or the tenant data version will be out of synch with the application version forcing you to perform a data upgrade for each tenant. I hope this answers your question, otherwise let us know.

Thanks
