### ISSUE TITLE
Microsoft-Application* symbols

### ISSUE THREAD

**Issue by madalinaCG** [MicrosoftDocs/dynamics365smb-devitpro-pb#3]
Hi, 
   You mentioned on a note that "If you are upgrading to Microsoft Dynamics NAV 2018 CU1, or higher, please use the symbols that you find in the ModernDev folder on the cumulative update DVD.", but for using In-Client Designer on a localized version of NAV 2018 CU2 it didn't worked without Microsoft-Application symbols published. 

Thanks,
Madalina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec2bde3-7aa2-0d9b-2d60-0fc57aa85645
* Version Independent ID: c37bcc83-3482-b533-8e9a-8feb56a6b88e
* Content: [Upgrading the Database - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/upgrading-the-data#AddExtensions)
* Content Source: [dynamics-nav/Upgrading-the-Data.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Upgrading-the-Data.md)
* Service: **unspecified**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Thanks for reporting this! The team will process this issue after the holidays.

**Comment by jswymer** [comment]
Hi Madalina,
Thanks for reporting this issue. I had a chance to take a look, following the guidelines in the article, but I could not reproduce the error. One thing that can happen is that when you run finsql.exe to generate the application symbols (Task 18, step 4 in the article), it can take several minutes for the process to complete – even though the command prompt indicates otherwise.  You can monitor the process using Task Manager. When the process ends, a file named navcommandresult.txt is saved to the Dynamics NAV Windows client installation folder. If the command failed, another file named naverrorlog.txt will be generated. 
If you can provide any more information about your experience, I would be happy to revisit this issue. In the meantime, I will update the article to include a note about the finsql.exe process. 
Thanks
John
