### ISSUE TITLE
"Become a Contributor to Business Central" link broken

### ISSUE THREAD

**Issue by eclipses** [MicrosoftDocs/dynamics365smb-devitpro-pb#3088]
"Become a Contributor to Business Central" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21e4aa27-1161-d502-7ef5-5a10c8c17839
* Version Independent ID: 8bfa326e-2d20-dcf2-551b-28b5fdd85741
* Content: [Create a New Module in the System Application - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-new-module)
* Content Source: [dev-itpro/developer/devenv-new-module.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/main/dev-itpro/developer/devenv-new-module.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by v-nithyamut** [comment]
Thanks for the feedback. We can't reproduce the broken link; it links to the [www.cloudblogs.microsoft.com](https://www.cloudblogs.microsoft.com/) and is an external link. Closing the issue for now, please re-open if this continues to be an issue. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. We're not able to reproduce the issue, we checked the links from different locations and machines. The link points to this location: https://cloudblogs.microsoft.com/dynamics365/no-audience/2018/08/28/become-a-contributor-to-business-central/ - and we'll update the article with this link instead - the existing link in the article seems to have a redirect. Please check if you can access this link. Thanks.

**Comment by eclipses** [comment]
Hi @SusanneWindfeldPedersen the url has been changes in the page, before had "www" and now it is without. I'm really surprised as rather than say "thank you we fixed the issue" you continue on repeating that you were not able to reproduce. Someone did a change and cannot be denied.

**Comment by SusanneWindfeldPedersen** [comment]
Hi @eclipses - Sorry for any misunderstanding - your feedback is much appreciated. We didn't change anything in the article yet - we are going to. Right now the article URL points to: 
[Become a Contributor to Business Central](https://blogs.msdn.microsoft.com/nav/2018/08/28/become-a-contributor-to-business-central/)  

but we'll update it to 
https://cloudblogs.microsoft.com/dynamics365/no-audience/2018/08/28/become-a-contributor-to-business-central/ 

with the next refresh, because we guessed that maybe some redirection isn't kicking in properly. We can access both URLs here, hence the "we cannot reproduce". Hope this explains the background. We'll get it updated soon. Thanks for your help.
