### ISSUE TITLE
Update path

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-devitpro-pb#36]
Hello, I am totally missing the path, when I want to update/upgrade the app. The article is just about installing and removing. But there is no clue what to do to install newer version of the app, and this will be most situations. I am installing on clean system only once, after that, each time, I am upgrading...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f8f5936-c5b1-b30c-3901-1df552d25fb9
* Version Independent ID: 7a97c5ec-ac40-db6d-425a-b463352bb662
* Content: [How to: Publish and Install an Extension - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/how-to--publish-and-install-an-extension)
* Content Source: [dynamics-nav/How-to--Publish-and-Install-an-Extension.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/How-to--Publish-and-Install-an-Extension.md)
* Service: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
It's somewhat convoluted at the moment because we're supporting two very different experiences with two very different technologies (extensions V1 and V2), as you know.

For extensions V2, the guidance is here: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions)

For extensions V1, the story broke precisely at upgrade - we didn't get around to anything other than seeing an updated extension as simply a 1:1 replacement. But of course, the updated extension should still have upgrade code to manage any schema changes or similar. Guidance for that in the article linked-to above for AL development.

I hope this answers your question?

**Comment by edupont04** [comment]
You're very welcome! And yes, the V2 content is still in process of being indexed by search engines, so it's not always easy to find. But https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/ is a good starting point. 

I'll close this issue, unless you object.

Thanks, and keep the feedback coming!
