### ISSUE TITLE
False statement or missing instructions?

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-devitpro-pb#366]
Remarks: "This property applies validation to the field."
If i.e. Email is chosen, user can still enter any value in a field.
Is the above mentioned statement false or are there some missing instructions to achieve validation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fde1227-7179-ab1e-9cbc-eb4415056328
* Version Independent ID: a377e4b5-e402-6d0f-30c8-7b056e89acee
* Content: [ExtendedDataType Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-extendeddatatype-property)
* Content Source: [dev-itpro/developer/properties/devenv-extendeddatatype-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-extendeddatatype-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback.
The default validation is performed automatically when the user inputs a value in a field. The input value can only be one of the valid field types defined for the chosen extended data type, as seen in the table. In the case of the Email, the value of the user input can only be of the types Code and Text. Otherwise, an error message will pop up. I hope this answers your question.
