### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by salgiza** [MicrosoftDocs/dynamics365smb-devitpro-pb#374]
The link in "Using OAuth to Authenticate Microsoft Dynamics NAV Web Services (Odata and SOAP)" does not work. 

It redirects to the partnersource, which requires login (I have a partnersource user, but it is a bit weird to hide this info from the public). Once logged in, it returns an error page.

Regards,
Salva

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0617e3b-c3af-7f9e-ec75-6f7c69866287
* Version Independent ID: c6bf5953-2917-9d3d-8dfc-29a2f53b3a1c
* Content: [Web Services Authentication - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/web-services-authentication)
* Content Source: [dev-itpro/webservices/Web-Services-Authentication.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/webservices/Web-Services-Authentication.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, the link target should be [Using OAuth to Authenticate Microsoft Dynamics NAV Web Services (OData and SOAP)](https://docs.microsoft.com/en-us/previous-versions/dynamics-nav-2016/mt634540%28v=nav.90%29). The link has been fixed in the article and an it will be published soon. Unfortunately, the content in the article is out-of-date. We are currently working on updating the content. This should be available soon as well. Thanks for the feedback!
