### ISSUE TITLE
SQL Connection String incorrect

### ISSUE THREAD

**Issue by SorenKlemmensen** [MicrosoftDocs/dynamics365smb-devitpro-pb#382]
It the documentation under "3. SQL Connection" the template connection string is given as "Server={ServerName};Initial Catalog={DatabaseName};UserID={SQL Authenticated UserName};Password={SQL Authenticated Password};"

This is wrong to my testing.
A working connection string would look like this
Server={localhost or SQL Server Name};Database={SQL Server Database Name};User Id={SQL Server Authenticated UserName};Password={SQL Server Authenticated Password};

Example: 
Server=localhost;Database=NAVPROD;User Id=sa;Password=P@ssw0rd1

(Don't worry the Password above is fake :-)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90bc5fad-1339-2f68-cfc7-ab24acd3d815
* Version Independent ID: 00690d59-5861-9f3d-a740-9057d333e965
* Content: [Intelligent Edge for on-premises - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/about-intelligent-edge)
* Content Source: [dev-itpro/administration/about-intelligent-edge.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/about-intelligent-edge.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by jswymer** [comment]
Hello, thanks for the feedback! The connection string listed was meant as an example of a connection string format, because the connection strings can vary. We provided a link to [FAQ:](https://blogs.msdn.microsoft.com/sqlforum/2010/12/20/faq-how-do-i-find-the-correct-server-or-data-source-value-for-an-sql-server-instance-in-a-connection-string/) as some guidance in determining the connection string. 

I made some slight changes to the article that will hopefully better clarify this, plus I added your example. The update will be published soon.  Thanks again.
