### ISSUE TITLE
Deleting symbols first

### ISSUE THREAD

**Issue by nickfaasen** [MicrosoftDocs/dynamics365smb-devitpro-pb#385]
A note is written telling: "If you experience problems with generating symbols, try to delete existing symbols first."
My question is how to do this?

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 156ead7e-1ab8-d9fb-44ca-e9029435e5a6
* Version Independent ID: 5a6899ff-c91d-d2ab-b3d6-0153808a106f
* Content: [Running C/SIDE and AL Side-by-Side - Business Central](https://docs.microsoft.com/nl-nl/dynamics365/business-central/dev-itpro/developer/devenv-running-cside-and-al-side-by-side)
* Content Source: [dev-itpro/developer/devenv-running-cside-and-al-side-by-side.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-running-cside-and-al-side-by-side.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, thanks for the feedback!

The note either needs to be expanded with some more information or removed to avoid confusion. 
How to delete the symbols would depend on where you are experiencing the problem. 

If you experience issues with generating symbols, the log file from the finsql.exe provides some insight into what went wrong. Symbol references are stored in the Object Metadata table of the database. If you need to delete the symbol references, then you use a query on the table. 

If the issue involves downloading and publishing symbols in Visual Studio code, then symbols can be deleted from the alpackages folder in the project.  

I hope this help, otherwise let us know.
Thanks
