### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-devitpro-pb#416]
"[Variables]...can be named using Pascal case, temporary variables have the Temp prefix, and objects must include the object name in the name." This is very clear and unambiguous. But "All variables remain unchanged when they are named" is not. The first does not actually explain the second. What does it mean, to "remain unchanged"? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7b7057-f9c5-6587-5d8b-267935685262
* Version Independent ID: 11a70e81-f0a2-ec66-d63e-d1b0b5edeb5c
* Content: [Best Practices for AL code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode)
* Content Source: [dev-itpro/compliance/apptest-bestpracticesforalcode.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your question. So the guidelines are as follows:

All variables remain as they were, meaning:
•	PascalCase
•	Temporary have Temp prefix
•	Objects must include object name in the name

Example:
TempCustomer: temporary Record Customer;
Vendor: Record Vendor;

Remain as they were refers to PreCal rules and should probably be left out - because this is confusing in the context. I will update the topic for the next refresh, thanks.
