### ISSUE TITLE
Not clear when to use the command Sync-NAVApp

### ISSUE THREAD

**Issue by KSH-audibene** [MicrosoftDocs/dynamics365smb-devitpro-pb#515]
It is not clear from the documentation when exactly the Sync-NAVApp command should be used (except Clean mode).
It seems, the app is synchronized automatically when I publish/install it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b108d9a5-aadd-4011-86e3-7241addc4206
* Version Independent ID: 5fdebecd-6373-6472-77bb-c9eb68dd10a2
* Content: [Sync-NAVApp (Microsoft.Dynamics.Nav.Apps.Management)](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/sync-navapp?view=businesscentral-ps)
* Content Source: [businesscentral-ps/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md](https://github.com/MicrosoftDocs/nav-docs-powershell/blob/live/businesscentral-ps/Microsoft.Dynamics.Nav.Apps.Management/Sync-NAVApp.md)

**Comment by jswymer** [comment]
I agree, the content could be clearer. In short, you must always run the Sync-NAVApp cmdlet against the tenant after you publish an extension ; otherwise you will not be able to install it. This must be done after the first version of the extension is published, and after each new version (as part of the upgrade process). At least, this should be the case. Let me know if you have experienced otherwise. 

In case you have not seen it yet, the use of Sync-NAVApp as part of installation and upgrade is described [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-how-publish-and-install-an-extension-v2](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-how-publish-and-install-an-extension-v2) and [Upgrading Extensions V2](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions).

 In the meantime, I will update the content to make this more clear.  Thanks for the feedback!

**Comment by jswymer** [comment]
The sync-navapp cmdlet help has been updated. The updated article will be published soon. Thanks for the feedback.
