### ISSUE TITLE
Microsoft SQL Server Report Builder

### ISSUE THREAD

**Issue by JohnnyUndercover** [MicrosoftDocs/dynamics365smb-devitpro-pb#566]
Which version of the "Microsoft SQL Server Report Builder" is required to edit the .rdl files? A link to the Microsoft SQL Server Report Builder download page would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b7f14d-d6ca-7248-7621-47669905bea0
* Version Independent ID: c1e289a5-c3cc-a748-4f59-6a56001c4b8d
* Content: [Creating an RDL Layout Report - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-howto-rdl-report-layout)
* Content Source: [dev-itpro/developer/devenv-howto-rdl-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-howto-rdl-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello, editing RDL report layouts requires Report Builder for SQL Server 2016. If you have an on-premises solution, this is available on the installation DVD and installed as part of Setup. Otherwise, you can download it from [here](https://www.microsoft.com/en-us/download/details.aspx?id=53613).

We also list the Report RDL requirements in the [System Requirements](https://docs.microsoft.com/en-gb/dynamics365/business-central/dev-itpro/deployment/system-requirement-business-central). The article has been updated with a link to the requirements. I hope this helps. Thanks for the feedback.
