### ISSUE TITLE
Error 0T

### ISSUE THREAD

**Issue by tantainiit** [MicrosoftDocs/dynamics365smb-devitpro-pb#587]
In AL code, If set time = 0T, it don't error syntax but it don't understand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08da475c-0713-23d5-29f7-02485deb07c6
* Version Independent ID: ea0a5d33-e7ba-2527-9c8c-60de9dcbeaf0
* Content: [Time Data Type - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/time/time-data-type)
* Content Source: [dev-itpro/developer/methods-auto/time/time-data-type.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/methods-auto/time/time-data-type.md)
* Service: **dynamics365-business-central**
* GitHub Login: @solsen
* Microsoft Alias: **solsen**

**Comment by blrobl** [comment]
Hi, thanks for your feedback. I don't fully understand your question, but setting the time to 0T is indeed possible (and hence will not generate a syntax error) because it is the unspecified value for time, used when you don't want to define a concrete moment in time. Therefore, when you print it as shown in the example you will get an empty box. I hope this answers it.

**Comment by tantainiit** [comment]
example, I have procedure:
    procedure CheckTimeIsZero(pInputTime: Time): Boolean
    begin
        if pInputTime = 0T then
            exit(true);
    end;

If I run function  in AL code:  
 - CheckTimeIsZero(TODAY) --> false
 - CheckTimeIsZero(0T) --> false -> wrong

And If I run function in C/AL Code:
 - CheckTimeIsZero(TODAY) --> false
 - CheckTimeIsZero(0T) --> true

**Comment by SusanneWindfeldPedersen** [comment]
Hello, please use your usual support channel for filing product bugs. Thanks.
