### ISSUE TITLE
Page Extensions

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#633]
Could information be added about whether all or which of all these are available on Page Extensions?
As per VS Code compiler, I can e.g. use both OnDeleteRecord and OnAfterGetRecord and I do not find any information about them, nor in which order page extension triggers are executed against the standard page triggers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0e36d7-395e-ed94-2e77-f7edb74e7757
* Version Independent ID: 1f838a73-fefc-8fbd-bcb9-cc9ad899dbdd
* Content: [Page and Action Triggers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-page-and-action-triggers)
* Content Source: [dev-itpro/developer/triggers/devenv-page-and-action-triggers.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/triggers/devenv-page-and-action-triggers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for the patience and feedback. Since this issue was opened, we have published auto-generated docs for triggers and these are sorted by object and element they can be used on, this structure can be seen in the table of contents. The extension triggers typically named so that by their name you can tell how they logically are triggered compared to the object triggers. We hope this helps and will close this issue. Thanks.
