### ISSUE TITLE
Windows 7 for Client

### ISSUE THREAD

**Issue by Charisty** [MicrosoftDocs/dynamics365smb-devitpro-pb#64]
Why Windows 7 is not mentioned on Supported operating systems for Windows Client Requirements section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f7491b-a29e-098a-60b9-419412fc317b
* Version Independent ID: efd427b0-5559-88b0-9c3d-740e16bd61b3
* Content: [System Requirements for Microsoft Dynamics NAV 2018 - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/system-requirements-for-microsoft-dynamics-nav)
* Content Source: [dynamics-nav/System-Requirements-for-Microsoft-Dynamics-NAV.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/System-Requirements-for-Microsoft-Dynamics-NAV.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by jswymer** [comment]
Hello, Windows 7 for the Windows client is not supported in Dynamics NAV versions after 2016.  Thanks for the feedback.

**Comment by Charisty** [comment]
@jswymer Thank you for your reply. But I try to install Dynamics NAV 2018 on Windows 7 It can be installed and work fine.

**Comment by jswymer** [comment]
Although it can be installed, we do not recommend using the Windows Client on Windows 7. The reasons for this are that Windows itself has been out of main stream support since January 2015 (https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet), plus we no longer test and hotfix for Windows 7 so we cannot gaurantee that all functionality works as intended. I hope this helps clarify things.

**Comment by Charisty** [comment]
OK, Thank you.
