### ISSUE TITLE
SQL Sever milliseconds precision

### ISSUE THREAD

**Issue by TheDoubeD** [MicrosoftDocs/dynamics365smb-devitpro-pb#663]
Maybe its important to add that SQL Server by default doesnt support Datetime with precision to 1 millisecond.
Example Code (maybe example with the biggest impact):
//Code before...
MyRecord."My Dattime Field" := CREATEDATETIME(31122018D,235959.999T);
MyRecord.MODIFY();
MyRecord.GET(); //MyRecord."My Dattime Field" will be retrieved as 01012019 000000.000T

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42219cef-3488-c016-4ece-860898e0bae8
* Version Independent ID: f769baa9-9454-30a5-b68d-0a9690bb93f6
* Content: [DateTime Data Type - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/datetime-data-type)
* Content Source: [dynamics-nav/DateTime-Data-Type.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/DateTime-Data-Type.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback and sorry for the long wait. This is a specific SQL Server behavior that is discussed on other communities. In general we want to refrain from documenting particular external product behavior because we do not monitor when or if an issue like this is fixed in a future release. Hope that makes sense. Thanks.
