### ISSUE TITLE
Adding language translation to standard D365 BC objects

### ISSUE THREAD

**Issue by gycsiak** [MicrosoftDocs/dynamics365smb-devitpro-pb#76]
Dear Microsoft D365 BC Team,

I would like to inquire information, how an extension 2.0 solution can be created to provide translation and caption in hungarian language to standard objects, that are not part of the extension and are created by Microsoft.

I see, that I can provide translation to our own extension, but it doesn't make sense, if the standard system is not translated.

Thank you in advance for your feedback,

Best regards,

Gyula Csiak
HRP Europe Ltd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8610a4-2eb0-7924-19a5-a2ab0d6b98a5
* Version Independent ID: a33fb833-bb5a-e54e-78aa-fbd6a61a088c
* Content: [Working with Translation Files - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-work-with-translation-files#translation-and-localization-apps)
* Content Source: [dev-itpro/developer/devenv-work-with-translation-files.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-work-with-translation-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. In order to translate the base app, you must export the .txt file from Dynamics NAV and translate the strings to hungarian. The translated .txt file can then be included in the .AL extension. The topic you reached has a link that describes how to export the .txt files. For more information also see [Development of a Localization Solution](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-develop-localization). Thanks.
