### ISSUE TITLE
Microsoft Dynamics 365 on premise integration with Business Central Online

### ISSUE THREAD

**Issue by thecrmsolutions** [MicrosoftDocs/dynamics365smb-devitpro-pb#773]
Hi,

Is it possible to do Microsoft Dynamics 365 on premise integration with Business Central Online using the above steps. Or this article deals with On-Premise version of both? Please clarify.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d13606d-1b5f-8061-ddbb-65bad9f63e29
* Version Independent ID: ef4faad8-2f82-cd9c-100f-1dc181db3974
* Content: [Preparing for Dynamics 365 for Sales for Integration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration#feedback)
* Content Source: [dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by ikoletic** [comment]
Business Central On line to Dynamics 365 Sales on premise integration is not supported due to authentication mechanism available in Business Central Online. Only supported authentication mechanism for Business Central Online to connect to Dynamics 365 Sales in through Office 365 Authentication. As you can see in this article [here](https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/mt608573(v=crm.8)?redirectedfrom=MSDN#connection-string-parameters) only supported authentication types for Dynamics 365 in on premise environment as AD, IFD and oAuth, but not Office 365.

**Comment by jswymer** [comment]
Thanks for the feedback! We will close this issue for now. If you have any additional feedback, let us know.
