### ISSUE TITLE
Link of "Business Central docs"

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#779]
The link text after "Business Central docs" (the very first link in this article) shows "https://docs.microsoft.com/dynamics365/business-central" but points to "https://docs.microsoft.com/en-us/dynamics365/business-central", hence to en-us. Not sure whether this was intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9c875d8-3401-cfe3-d7d8-aac436b2b53b
* Version Independent ID: 4459ce33-7e99-adf3-591a-a665e3db0067
* Content: [Resources for Help and Support - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help-and-support)
* Content Source: [dev-itpro/help-and-support.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/help-and-support.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Nathalie,
Thanks for identifying this! The underlying link is actually set up to reflect the browser locale, but because it is (nearly) always being accessed from a page that is rendered in en-US (since we do not translate the developer and IT-pro content), it will always render as en-US....
I'll try to reconfigure it to render as the browser locale.

**Comment by edupont04** [comment]
This is now fixed, I hope.
