### ISSUE TITLE
deprecated values

### ISSUE THREAD

**Issue by TheDenSter** [MicrosoftDocs/dynamics365smb-devitpro-pb#807]
Bullet 15 mentions deprecated values for the Target attribute (Internal and Extension as opposed to OnPrem and Cloud). I'm not sure if 'external' is still accepted, or if there is a date for when that won't be accepted anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b8f96f-eb61-aa86-ed4f-4544e9808aef
* Version Independent ID: fabff680-eeb9-26b4-5253-04713e0e1c74
* Content: [Rules and Guidelines for AL Code - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-overview)
* Content Source: [dev-itpro/compliance/apptest-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **rweigel**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for your feedback. You hit a topic that needed an update to use Cloud and OnPrem, so that was good to get fixed. I am not sure how long you will be able to use the deprecated values, but I'd recommend shifting to the new ones as soon as possible and when your AL extension allows. The topic will be fixed with the next doc refresh. Thanks.

**Comment by TheDenSter** [comment]
Thanks Susanne, it's very cool to have this kind of feedback mechanism
