### ISSUE TITLE
Deprecated Features & Fields for W1 version

### ISSUE THREAD

**Issue by lhtan-dev** [MicrosoftDocs/dynamics365smb-devitpro-pb#810]
As many parts of the world are using W1 version, can you add the references for deprecated features & fields for the W1 version of Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 099e4c9c-6893-2d35-6ece-6c056a2c752f
* Version Independent ID: 8a51d9d5-605d-d442-337b-ef992d25395d
* Content: [Fields that are Moved, Removed, or Replaced - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-fields#feedback)
* Content Source: [dev-itpro/upgrade/deprecated-fields.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/deprecated-fields.md)
* Service: **dynamics365-business-central**
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Hello, we are currently working on an article that will about deprecated features for W1. Hopefully this will be published soon. On an object level (tables, fields and methods), you can refer to [Breaking Changes](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md). This article is published on the ALAppExtensions repo in GitHub. Eventually this content will probably be moved into the documentation but for now, because it is frequently updated as we discover missing info, it will remain here. I hope this helps. Thanks for the feedback!
