### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by befabry** [MicrosoftDocs/dynamics365smb-devitpro-pb#854]
Broken link for : "Walkthrough: Configuring Web Services to Use SSL (SOAP and OData)" in the second _Important_ helper of the page [Authentication and Credential Types for Dynamics 365 Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/users-credential-types)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1fd7a9e-7ba2-62b1-14bd-6e45e15b26ff
* Version Independent ID: da31ff3b-726f-03a8-f05a-4e2d7d8e694d
* Content: [Users and Credential Authorization - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/users-credential-types)
* Content Source: [dev-itpro/administration/users-credential-types.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/users-credential-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this - the broken link will be fixed with the next refresh of the docs. The link was supposed to point to the following topic: [How to: Implement Security Certificates in a Production Environment](https://docs.microsoft.com/en-us/dynamics-nav/How-to--Implement-Security-Certificates-in-a-Production-Environment). Thanks.
