### ISSUE TITLE
Open in Excel

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [MicrosoftDocs/dynamics365smb-devitpro-pb#866]
We have installed BC Spring CU04 No on-prem at client site. The customer i running his own AD and not using Azure AD. When we run the the action "Open in Excel" from the web client it opens the Excel with the data from the page but the user is not be able to use the Refresh button. The same action works from the RTC client and the user can choose to Refresh and the data are refreshed.  Our problem/question is it the correct functionality that the Refresh button is disabled when we run the action from the web client or do we have some configuration issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5c53847-a111-f746-cc85-af3dcc702f84
* Version Independent ID: 06c03c31-a8a9-40e7-2847-bc22cea91344
* Content: [Setting up the Excel Add-In for Editing Data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/configuring-excel-addin#feedback)
* Content Source: [dev-itpro/administration/configuring-excel-addin.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/administration/configuring-excel-addin.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,
In the web client, the **Open in Excel** action does not allow you to push data back into Business Central. If you want this functionality from the web client, you will have to configure the Excel Add-in as described in the linked article. When this add-in is configured, an **Edit in Excel** action is made available on pages in the web client. With this action you can refresh data from Excel to Business Central.

If the **Open in Excel** action in the RTC (Windows) client includes a Refresh option, this is probably because you have installed the Excel Add-in that is part of the Business Central installer. However, this particular add-in pertains only to the Windows client. It is a bit confusing I admit. I hope this helps, otherwise let us know.

Thanks for the feedback!

**Comment by JonFjolnirAlbertsson** [comment]
Thank you jswymer,
So there are to different add-ins for the **Open in Excel** action. One for the Windows Client and one for the Web Client. The Windows client add-in supports Refresh action from Excel. The Web client add-in does not support Refresh action from Excel.
