### ISSUE TITLE
Printing this walkthrough

### ISSUE THREAD

**Issue by martinjordt** [MicrosoftDocs/dynamics365smb-devitpro-pb#88]
Hi MS,
Please check the Download PDF link in the lower left corner. It points to a 800 page document that has nothing to do with this walkthrough...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4651c5b4-e7a3-8b92-e4c8-957eda3b2c11
* Version Independent ID: c2aa03c0-b72e-2d4f-3f13-8b2265676fe0
* Content: [Dynamics 365 for Sales integration - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--customizing-microsoft-dynamics-crm-integration-in-dynamics-nav)
* Content Source: [dynamics-nav/Walkthrough--Customizing-Microsoft-Dynamics-CRM-Integration-in-Dynamics-NAV.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Customizing-Microsoft-Dynamics-CRM-Integration-in-Dynamics-NAV.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04

**Comment by edupont04** [comment]
Hello Martin,
That's right - the Download PDF button generates a PDF file for the entire docset, meaning all articles in the developer- and ITpro content for Dynamics NAV 2018. This is by design and applies to all products where the content is published to the Docs.microsoft.com site.

If you want to print this particular article, you can use the print functionality of your browser - for example, in Edge, you can right-click and then choose Print. Optionally, you can use the Microsoft Print to PDF feature in Windows 10, for example.

I hope this helps you understand how the Docs.microsoft.com site works.
