### ISSUE TITLE
Still supported in webclient?

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-devitpro-pb#885]
Enabling / disabling this property seems to make no difference on the webclient. In both cases, the icon is show with the same size. Does it really still make sense using this property in the modern clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0865ca2c-f735-3e44-16da-a78607034dda
* Version Independent ID: 46b76622-068b-c705-8e2b-346e7fda961e
* Content: [PromotedIsBig Property - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-promotedisbig-property)
* Content Source: [dev-itpro/developer/properties/devenv-promotedisbig-property.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/properties/devenv-promotedisbig-property.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,
Thanks for the feedback. The property does have an effect in the web client, however it is not obvious and does not have the same effect as earlier. Unlike in the old Windows client, it will not show the large icon. What it does is place the action as the first action in the action bar. For example, in the following code snippet, the Sales Invoice action is defined after the Sales Quote action, However, because the PromotedIsBig property is true, then in the web client, it will appear before the Sales Quote action:
 
`actions
    {
        area(Creation)
        {
            action("Sales Quote")
            {
                Promoted = true;
                PromotedCategory = Category5;  // PromotedActionCategories = New Document
                PromotedOnly = true;
                Image = NewSalesQuote;
                ApplicationArea = All;
            }
            action("Sales Invoice")
            {
                Promoted = true;
                PromotedCategory = Category5;  // PromotedActionCategories = New Document
                Image = SalesInvoice;
                PromotedIsBig = true;
                ApplicationArea = All;
                trigger OnAction()
                begin
                end;
            }
        }`
  If there is more than one action set to PromotedIsBig, then the appers first, in the order defined. 

We will update the article to explain this.

**Comment by jswymer** [comment]
The article has been updated. We will close this issue but feel free to provide more feedback. Thanks!
