### ISSUE TITLE
How to upgrade other Server instances web server components?

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#895]
After upgrade all is fine with standard Server instance BC150

But we have many instances and when user tries to logon thru BCAAD instance, they get error:
"The build version of your client or of the web server components is different from the build version of the server instance that you connect to. However, your connection works. Client version: 15.0.36510.0 Server version: 15.0.37898.0"

So please add to instructions how to upgrade web server components for non default Server instances.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello,
For the non-default instances, you use PowerShell cmdlets in the Business Central Administration Shell, for example:
1.	Copy the navsettings.json file for the web server instance somewhere so that you can reuse it.
2.	Run the [Remove-WebServerInstance cmdlet](https://docs.microsoft.com/powershell/module/navwebclientmanagement/remove-navwebserverinstance) to delete the existing web server instance.
    ```
    Remove-NAVWebServerInstance -WebServerInstance <web service instance name>
    ```
3.	Run the [New-NavWebServerInstance cmdlet](https://docs.microsoft.com/powershell/module/navwebclientmanagement/new-navwebserverinstanc) to recreate the web server instance.
    ```
    New-NAVWebServerInstance -ServerInstance <BC server instance name> -WebServerInstance <web server instance name> -Server <server computer name>
    ``` 
4.	Copy the old navsettings.json file to the web server instance directory.

**Comment by erolkunman** [comment]
ok -thanks.
