### ISSUE TITLE
Start-NavDataUpgrade missing

### ISSUE THREAD

**Issue by eivindgiske** [MicrosoftDocs/dynamics365smb-devitpro-pb#898]
Hi,
After having followed this, the tenant state seems to be OperationalDataUpgradePending, and one cannot proceed with third-party extension installation:
install-navapp : Cannot install apps due to the state of the tenant: OperationalDataUpgradePending.
Is there a missing step?

After having run Start-navdataupgrade, I can proceed. But I am unsure what it does, as everything is now extensions, and we have executed start-navappdataupgrade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15#feedback)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hi, Thanks for the feedback.

In the cumulative update scenario, for example going from 15.0 to 15.1, running Start-NAVDataUpgrade probably does not do much because the data upgrade is done by the Start-NAVAppDataUpgrade for each extension. So there is nothing wrong with running it. The question is how did the database get to the OperationalDataUpgradePending state. Usually, this state only occurs if the application version of the database (found in the $ndo$dbproperty table) is greater than the tenant version (found in the $ndo$tenantdatabaseversion table).

**Comment by jswymer** [comment]
Hello, I will close this issue for now. I hope this answered your question. If you have any more feedback, let us know and I will re-open the issue. Thanks for the feedback.
