### ISSUE TITLE
Database Conversion fails 15.1->15.2

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-devitpro-pb#934]
This is basically a continuation of issue #879 "Database Conversion fails)
Last time the solution was to restart PowerShell, after installing new cumulative BC.

But now that does not help me.
I get error:
Invoke-NAVApplicationDatabaseConversion : A technical upgrade of database 'Demo Database BC (15-0)' on server 'EROL-T470\BCDEMO' cannot be run, because the database’s application version '130581' is greater than or
 equal to the platform version '130581'.

However my server instance started without issues and the upgrade of System and Base app was also a success.

Does this mean that upgrading from 15.1-&gt;15.2 we dont have to do a Database Conversion?
If Yes, then this information should clearly be stated in upgrade manual.

(We are dealing with precious customer databases here and any error with database during upgrade makes the blood pressure rise dramatically.-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e71477e4-f2ea-1481-7597-29b324bd4f57
* Version Independent ID: a2bb3a05-e5c1-d9f7-f47f-d2f34c4a91ea
* Content: [Install an update - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-cumulative-update-v15)
* Content Source: [dev-itpro/upgrade/upgrading-cumulative-update-v15.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/upgrade/upgrading-cumulative-update-v15.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by erolkunman** [comment]
Upvoting my question:
Does this mean that upgrading from 15.1->15.2 we dont have to do a Database Conversion?

**Comment by jswymer** [comment]
Hello, Thanks for the feedback!

We did some investigation and can also reproduce the issue. I understand the confusion, and the article needs to be fixed to reflect the 15.1 to 15.2 update. The short answer is that when going from 15.1 to 15.2, you do not have to run the database conversion. No harm is done if you do run the cmdlet though.
 
A database conversion is required when schema changes have been made to the system tables, which is not the case from 15.1 to 15.2. However, it is the case when going from 15.0 to 15.1 or from 15.0 to 15.2, so you must run the database conversion.  When a database conversion is required, you will not be able to start the BC server instance against the database. If you try, you will get an error that the database must be converted.
 
The error thrown by the cmdlet is misleading for a couple reasons. First, it is more of an informational message, and it registers as a warning in event log. Also, the “application version“ shown in the message is actually the value of the databaseversionno column in the dbo.$ndo$dbproperty table of the application database. There is also a hard-coded version in the platform. We increase the hard-coded platform version for an update whenever schema changes have been made to system tables. When you run the Invoke-NAVApplicationDatabaseConversion cmdlet, it compares the databaseversionno value to the hard-coded platform version. If the databaseversionno value is less than the platform version, then the conversion will run. 
 
I hope this answers your question, otherwise let us know. We will update the article in the meantime. Thanks!

**Comment by jswymer** [comment]
Hello, The article has been updated to make this more clear. The update will be published soon. We will close this issue for now. If you have more feedback, we will reopen it. Thanks!
