### ISSUE TITLE
2 dataitem at same level in Query

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-devitpro-pb#940]
Hi,

I'm trying to link the customer table to 2 other tables where the customer would be linked to both the "Payment Terms" and the contact table at the same time. 

The link between the "Payment Terms" table and the customer table should work as follow:
- DataItemLink = "Code" = Customer."Payment Terms Code";

The link between the "Contact" table and the customer table should work as follow:
- DataItemLink = "No." = Customer."Primary Contact No.";

I'm getting an error... You cannot combine two DataItems at the same level because unions are not supported.AL(AL0342)
This is a simple SQL process. Why is this not supported in AL.

How would I display the terms description and the primary contact info in my query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5400914d-d9a4-8bb0-e7f4-814b1476f8ee
* Version Independent ID: f8b799e6-614b-4a2f-4cdb-4d25f4499bec
* Content: [Query Object - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-query-object)
* Content Source: [dev-itpro/developer/devenv-query-object.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-query-object.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by HubGitke** [comment]
Thank you for posting this. On my opinion this is a real lack or even an error.

What we just want is something like:
 
```
Select 
A.Field1, A.Field2, B.Field1, B.Field2, C.Field1, C.Field2
From 
A,B,C
Where 
     A.Key = B.KeyOfA
  and C.Key = B.KeyOfC
```
This is no union, just a join connected by foreign keys. The common use of creating sql statements over more than one table.
So the errormessage AL0342 is wrong. 

I would expect an union, if there were further DataItems on the same level directly below the elements section. This is not the case. 

I am dissappointed, that no third table can be joined as it looks to me. 

It should work, because the DataItemLinks to the upper DataItem are pointing to different fields.

Imagine a table like an entry table that holds many foreign primary keys to linked master data tables.
You want to filter the entries by properties that are stored in the master data table. 

This is just a standard requirement on relational data retrival. The query object should provide it.

**Comment by SusanneWindfeldPedersen** [comment]
Thanks for your feedback. This repo is used for documentation feedback. Please go to [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) to suggest a product feature. Thanks
