### ISSUE TITLE
Function Types

### ISSUE THREAD

**Issue by NKarolak** [MicrosoftDocs/dynamics365smb-devitpro-pb#960]
I am missing very relevant information about Function Types, along with code examples: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-methodtype-property-upgrade-codeunits
Or is there some other landing page for creating Upgrade Codeunits? I could not find anything.

Edit: it seems the functionality is removed in BC 15. It would be useful to have it mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aad761f-ad97-7f15-fd0b-81f5716d2d90
* Version Independent ID: d0f0fb7c-6a1f-efef-e43c-955bb10b1404
* Content: [Upgrading an Extension V2 to a new version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions)
* Content Source: [dev-itpro/developer/devenv-upgrading-extensions.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-upgrading-extensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **solsen**

**Comment by jswymer** [comment]
Hello,

Thanks for the feedback. The documentation needs to be updated and improved. We have a work item to address this. 

You are correct that in BC 15, as a result of the transition to AL extensions only, the implementation for upgrade codeunits has changed. The content in the [Method Type] (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-methodtype-property-upgrade-codeunits) article is misleading because it refers more to upgrade codeunits implementation for upgrading data when using a C/AL base application in BC 14. 

If you are writing upgrade code for an extension, you can follow the guidelines in [Upgrading Extensions](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions).

If you are writing upgrade code to upgrade data for the C/AL base application in BC 14, you can refer to the NAV 2018 content at [Upgrade Codeunits](https://docs.microsoft.com/en-us/dynamics-nav/upgrade-codeunits). Unfortunately, this content has not yet been included in BC 14 help.

I hope this provides some insight. Thanks.

**Comment by SusanneWindfeldPedersen** [comment]
Closing for now, we have a work item to address the documentation work. Thanks.
