### ISSUE TITLE
Invalid URL's and mixing up of V1 and V2

### ISSUE THREAD

**Issue by spursrox** [MicrosoftDocs/dynamics365smb-devitpro-pb#984]
In section 2 at the very beginning, this is not a valid URL: 
Use Azure Active Directory (AAD) based authentication against the common API endpoint: https://api.businesscentral.dynamics.com/v2.0//api/v1.0

Also, its very confusing to have "V1.0" and "v2.0" all over the place, intermixed.  Which is it, V1 or V2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e026c87e-6bbe-9e7c-5ecc-e6f2943e2655
* Version Independent ID: 81cb7f00-6d48-4d29-b47c-b9bc36ad87d8
* Content: [Getting Started Developing Connect Apps for Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-connect-apps#feedback)
* Content Source: [dev-itpro/developer/devenv-develop-connect-apps.md](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/developer/devenv-develop-connect-apps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SusanneWindfeldPedersen** [comment]
Hello, thanks for catching this - the link https://api.businesscentral.dynamics.com/v2.0//api/v1.0 is because of formatting in the markdown file missing an important part, it is supposed to look like this: https://api.businesscentral.dynamics.com/v2.0/<environment name>/api/v1.0 - that's the valid URL. This will be fixed with the next refresh of the docs. The versioning of the APIs is the way it is. Thanks.
